"""测序表添加特殊操作记录字段

Revision ID: 28df1c07b903
Revises: fe7cd5db93d7
Create Date: 2020-12-16 09:10:10.609118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28df1c07b903'
down_revision = 'fe7cd5db93d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_operation', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.drop_column('special_operation')

    # ### end Alembic commands ###
