"""病人信息添加 样本来源字段

Revision ID: 7bbbedfdb77a
Revises: 19b43bacdb81
Create Date: 2020-12-15 14:27:19.996949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bbbedfdb77a'
down_revision = '19b43bacdb81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_origin', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('sample_origin')

    # ### end Alembic commands ###
