"""测序批次

Revision ID: 8d11f8aa45fe
Revises: a84ec68c381a
Create Date: 2020-12-16 14:41:20.428442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d11f8aa45fe'
down_revision = 'a84ec68c381a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch', sa.String(length=255), nullable=True))

    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.drop_column('batch')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('batch')

    # ### end Alembic commands ###
